### ISSUE TITLE
yaml example needed

### ISSUE THREAD

**Issue by sergeysaley** [jlmaroto/esp-home-vl53L1x#1]
Please tell how to use Your external component.

My test config:

```
substitutions:
  external_components_source: github://jlmaroto/esp-home-vl53L1x/components/vl531lx

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

i2c:
  sda: D2
  scl: D1
  scan: true
  frequency: 400kHz

sensor:
  - platform: vl53l1x
    name: "Distance"
    accuracy_decimals: 0
    unit_of_measurement: "mm"

```
Got in logs:

```
INFO ESPHome 2025.2.2
INFO Reading configuration /config/esphome/esphome-web-203ae5.yaml...
INFO Updating https://github.com/jlmaroto/esp-home-vl53L1x.git@None
INFO Unable to import component vl53l1x.sensor: No module named 'esphome.components.vl53l1x'
Failed config

sensor.vl53l1x: [source /config/esphome/esphome-web-203ae5.yaml:30]
  
  Platform not found: 'sensor.vl53l1x'.
  platform: vl53l1x
  name: esphome-web-203ae5 Distance
  accuracy_decimals: 0
  unit_of_measurement: mm```

**Comment by AbelDanger23** [comment]
I was able to get a little further but not getting any readout from the sensor.  Here is my yaml, using it to measure the softener salt level in my water softener

```
esphome:
  name: saltlevel
  friendly_name: saltlevel
  libraries:
    - "Wire"
    - "adafruit/Adafruit VL53L1X@^3.1.2"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: my_key

ota:
  - platform: esphome
    password: my_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Saltlevel Fallback Hotspot"
    password: my_password

captive_portal:

# I2C Configuration
i2c:
  sda: GPIO5
  scl: GPIO6
  scan: true
  frequency: 400kHz

external_components:
  - source:
      type: git
      url: https://github.com/jlmaroto/esp-home-vl53L1x.git
      ref: master
    #components: [ vl531lx ]

sensor:
  - platform: vl531lx
    name: "Distance"
    accuracy_decimals: 0
    unit_of_measurement: "mm"
    #address: 0x29
    filters:
      - offset: -850
      - multiply: -1
```

**Comment by AbelDanger23** [comment]
Got a temporary fix by adding this external component from this page: https://github.com/robertklep/esphome-custom-component.  It works with my original code until I can figure out how to properly do an external component.

```external_components:
  - source:
      type: git
      url: https://github.com/robertklep/esphome-custom-component
    components: [ custom, custom_component ]```

**Comment by sergeysaley** [comment]
I found github://soldierkam/vl53l1x_sensor, it works according to esphome.io specifications for external components.

My working config:

```
external_components:
  - source: github://soldierkam/vl53l1x_sensor
    refresh: 0s

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  frequency: 400kHz

sensor:
  - platform: vl53l1x_sensor
    name: ${device_name} distance    
    distance_mode: MEDIUM
    signal_threshold: 512
    update_interval: 15s
    accuracy_decimals: 3
    roi_center: 199
    roi_size:
      x: 9
      y: 9
    ambient_rate_sensor: 
      name: "Ambient Rate [MCPS]"
    avg_signal_rate_sensor: 
      name: "Average Signal Rate [MCPS]"
    peak_signal_rate_sensor: 
      name: "Peak Signal Rate [MCPS]"
    range_status_sensor:
      name: "Range Status"
```
